version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.15.0-browsers


    working_directory: ~/agnostic-web-foundation

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      #      # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

  
      - run:
          name: Install Application
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      
      - run: npm run build

      # - run: bash <(curl -s https://codecov.io/bash)

      - run: export NODE_ENV=CI && npm run test
